### ISSUE TITLE
Pattern should use backreference

### ISSUE THREAD

**Issue by Cheatoid** [Le0Developer/luapack#2]
https://github.com/Le0Developer/luapack/blob/c1adbfaeb9d6c7370383ea50fcd93c693698dad9/luapack.yue#L2

For example, this is not correctly matched with the current pattern:
`require "cheatoid's lib"`

**Comment by Le0Developer** [comment]
Thanks! I didn't know lua patterns had backreferences.

Fixed in 9811ce23625014fc78b1244ccc95fbd8dbb94c3f
